name: secrets-env-demo

on: [push]

jobs:
  use-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: use MY_SECRET_MESSAGE as env variable
        env:
          SECRET_MSG: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          echo "The secret is set: true"
          echo "Length of secret is ${#SECRET_MSG}"

      - name: Docker login uisng secrets
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "Logging into Docker Hub..."
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
