name: Smart Triggers

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - 'src/**'
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Triggered by changes in src/ or app/"'
